# Generated by Django 3.0.8 on 2020-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linkToProject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
