# Generated by Django 3.1.1 on 2020-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200908_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(null=True, path='/home/coding/django/personal_portfolio/static/img'),
        ),
    ]
