# Generated by Django 3.1.1 on 2020-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200908_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detailedDescription',
            field=models.TextField(default='insert description here'),
            preserve_default=False,
        ),
    ]
